package com.mybatis.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.last_name
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.gender
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.email
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.d_id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.id
     *
     * @return the value of tb1_employee.id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.id
     *
     * @param id the value for tb1_employee.id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.last_name
     *
     * @return the value of tb1_employee.last_name
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.last_name
     *
     * @param lastName the value for tb1_employee.last_name
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.gender
     *
     * @return the value of tb1_employee.gender
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.gender
     *
     * @param gender the value for tb1_employee.gender
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.email
     *
     * @return the value of tb1_employee.email
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.email
     *
     * @param email the value for tb1_employee.email
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.d_id
     *
     * @return the value of tb1_employee.d_id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.d_id
     *
     * @param dId the value for tb1_employee.d_id
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}