package com.mybatis.dao;

import com.mybatis.bean.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbggenerated Tue Dec 11 16:27:21 CST 2018
     */
    int updateByPrimaryKey(Employee record);
}